name: Code Health
description: Suggest code fixes or enhancements for LÖVE Potion
title: "[Code Health]: "
labels: [code]
body:
  - type: markdown
    attributes:
      value: "**Before submitting, please note this is essentially a 'to-do' for code cleanup. If you would like to contribute, please file a pull request instead.**"
  - type: textarea
    id: description
    attributes:
      label: Details
      description: Describe the what's wrong.
      placeholder: The code for file x is hard to read/causes issues.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Describe what can be done to fix it.
      placeholder: We can make it better with y.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Further elaborate on any key points about this.
      placeholder: Add any other context.
    validations:
      required: true
