name: LÖVE Potion

on:
  push:
    branches:
      - dev/3.0
  pull_request:

jobs:
  first:
    name: 3DS
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/3ds/bin/arm-none-eabi-cmake -S . -B build

      - name: Patch luasocket
        run: patch -d build/luasocket/libluasocket -N -i platform/ctr/libraries/luasocket.patch

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo 3DS-${{ steps.commit.outputs.short }}
          path: build/*.3dsx

  second:
    name: Switch
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake -S . -B build

      - name: Patch luasocket
        run: patch -d build/luasocket/libluasocket -N -i platform/hac/libraries/luasocket.patch

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Switch-${{ steps.commit.outputs.short }}
          path: build/*.nro

  third:
    name: Wii U
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -S . -B build

      - name: Patch luasocket
        run: patch -d build/luasocket/libluasocket -N -i platform/cafe/libraries/luasocket.patch

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Wii U-${{ steps.commit.outputs.short }}
          path: build/*.wuhb

  fourth:
    name: 3DS (Debug)
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/3ds/bin/arm-none-eabi-cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Patch luasocket
        run: patch -d build/luasocket/libluasocket -N -i platform/ctr/libraries/luasocket.patch

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo 3DS (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.3dsx

  fifth:
    name: Switch (Debug)
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Patch luasocket
        run: patch -d build/luasocket/libluasocket -N -i platform/hac/libraries/luasocket.patch

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Switch (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.nro

  sixth:
    name: Wii U (Debug)
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Patch luasocket
        run: patch -d build/luasocket/libluasocket -N -i platform/cafe/libraries/luasocket.patch

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Wii U (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.wuhb
